[Logging]
log_retention_days = 7

[App:LDTPapp]
DeleteDir = C:\Shinseikai\LDTPapp
CopySrcDir = C:\Shinseikai\Latest_version
CopyDestDir = C:\Shinseikai\LDTPapp

[Settings]
directories =
    \\Ajisai\ganka\LDTPapp\temp
    \\Jimtower\医局\医療秘書課\情報システム\眼科手術指示確認\output
    C:\Users\yokam\Desktop\Magnate\ファイル削除

extensions = xlsx, xlsm
# ログファイルの出力設定（yes/no）
enable_logging = yes
log_filename = cleanup.log